### ISSUE TITLE
was the recent ordering change of the id column intentional?

### ISSUE THREAD

**Issue by ajdamico** [CSBLatvia/vardpoor#10]
in the minimal reproducible example below, compare the `IDd` column in the two results.  vardpoor version `0.8.4` shows 1, 2, 3, 4, etc.  vardpoor version `0.8.6` shows 1, 10, 100, 1000, 10000, etc. which makes me think the id column is getting treated as a factor.  it is the cause behind our test cases breaking at https://travis-ci.org/DjalmaPessoa/convey so i'd like to know that this is a permanent, intentional change before i fix our test cases?  it is not mentioned in https://cran.r-project.org/web/packages/vardpoor/NEWS so i'm not sure whether it was intended?  thanks a lot   cc @djalmapessoa @guilhermejacob

	# sha identifier from 0.8.4 cran submission at https://github.com/CSBLatvia/vardpoor/commit/16c8939c1eacc1c82383fb1a9135e8d0075ee3df
	devtools::install_github( "CSBLatvia/vardpoor/vardpoor" , ref = "16c8939c1eacc1c82383fb1a9135e8d0075ee3df" )

	library(vardpoor)

	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	dati = data.frame(1:nrow(eusilc), eusilc)
	colnames(dati)[1] <- "IDd"
	dati <- data.frame(IDd = 1:nrow(eusilc), eusilc)
	vardpoor_gini_084 <- lingini(Y = "eqincome", id = "IDd", weight = "rb050", dataset = dati)

	vardpoor_gini_084
	  
	# current version 0.8.6
	devtools::install_github( "CSBLatvia/vardpoor/vardpoor" )
	  
	library(vardpoor)

	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	dati = data.frame(1:nrow(eusilc), eusilc)
	colnames(dati)[1] <- "IDd"
	dati <- data.frame(IDd = 1:nrow(eusilc), eusilc)
	vardpoor_gini_086 <- lingini(Y = "eqincome", id = "IDd", weight = "rb050", dataset = dati)

	vardpoor_gini_086

**Comment by JBreidaks** [comment]
Starting from 0.8.6 in function lingini and other EU-SILC functions ID always converts to character.

https://github.com/CSBLatvia/vardpoor/commit/6a1bd289f8736112e9816ef30994793d4df401c5

library(vardpoor)

data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
dati <- data.frame(IDd = paste0("V", 1:nrow(eusilc)), eusilc)
vardpoor_gini_090 <- lingini(Y = "eqincome", id = "IDd", weight = "rb050", dataset = dati)

vardpoor_gini_090

**Comment by ajdamico** [comment]
got it.  thanks very much
