### ISSUE TITLE
possible to check for whole number rather than integer type?

### ISSUE THREAD

**Issue by ajdamico** [CSBLatvia/vardpoor#11]
hi, just a suggestion to make your software easier for new users?  inside the `check_var` function you've got this integer0010 check:  https://github.com/CSBLatvia/vardpoor/blob/master/vardpoor/R/domain.R#L62-L64

the help page of `?is.integer` describes a check for whole numbers rather than integer types.  switching these lines over to the function `is.wholenumber` rather than `is.integer` would drop the requirement that users put a capital `L` at the end of their numbers?

no problem if you disagree or if i'm overlooking something..thank you!!

**Comment by ajdamico** [comment]
affects your code as well as ours ;)  https://github.com/CSBLatvia/vardpoor/pull/13

**Comment by JBreidaks** [comment]
https://github.com/CSBLatvia/vardpoor/commit/b93b74ff93a22f8f7a912f76962d3ea3ab21114b
