### ISSUE TITLE
Changes to pass next data.table release

### ISSUE THREAD

**Issue by mattdowle** [CSBLatvia/vardpoor#18]
Hi Juris,
The next data.table has two changes that affect `vardpoor`. I hope these changes are ok.  Could you update on CRAN please?
[Rdatatable/data.table#3310](https://github.com/Rdatatable/data.table/pull/3310)
[Rdatatable/data.table#3347](https://github.com/Rdatatable/data.table/issues/3347)
I've forked vardpoor and tried to submit a PR.  However the version here on GitHub is 0.9.10.  On CRAN you are up to 0.12.0.  Is the GitHub repo out of date or moved somewhere else?  So here are the changes (to 0.12.0 as on CRAN) in text form `diff`.  I checked that vardpoor passes OK with the next release of data.table, with these changes (there are no other changes needed).
```
$ diff vardchangespoor.R
224c224
<   cros_var_grad[, nameYs := rep( namesD(cros_var_grad[,"type"], cros_var_grad[,names(Dom),with = FALSE]), length.out=.N) ]
---
>   cros_var_grad[, nameYs := namesD(cros_var_grad[, "type"], cros_var_grad[, names(Dom), with = FALSE])]
253d252

$ diff vardchanges.R
324,326c324,326
<   saraks[, vstrata1 := paste0(" rot_1 : ", dataHq1, " ")]
<   saraks[, vstrata2 := paste0(" rot_2 : ", dataHq2, " ")]
<   saraks[, vstrata12 := paste0(" rot_1 : rot_2 : ", dataHq1, " : " , dataHq2, " ")]
---
>   saraks[, vstrata1 := paste0(" rot_1 : ", get("V1"), " ")]
>   saraks[, vstrata2 := paste0(" rot_2 : ", get("V2"), " ")]
>   saraks[, vstrata12 := paste0(" rot_1 : rot_2 : ", get("V1"), " : " , get("V2"), " ")]
534c534
```

The 2nd one is related to this change : 
> As promised in new feature 6 of v1.11.6 Sep 2018 (see below in this file), the datatable.CJ.names option's default is now TRUE. In v1.13.0 it will be removed.

and that item in v1.11.6 was : 

> New options(datatable.CJ.names=TRUE) changes CJ() to auto-name its inputs exactly as data.table() does, #1596. Thanks @franknarf1 for the suggestion. Current default is FALSE; i.e. no change. The option's default will be changed to TRUE in v1.12.0 and then eventually the option will be removed. Any code that depends on CJ(x,y)$V1 will need to be changed to CJ(x,y)$x and is more akin to a bug fix due to the inconsistency with data.table().

vardpoor is the only package affected by this CJ change I think.

Best, Matt

**Comment by JBreidaks** [comment]
Bug corrected https://github.com/CSBLatvia/vardpoor/commit/e7190a141b863239e2331b649344243342c34d3d
