### ISSUE TITLE
please help isolate data.table code that crashes R console with vardpoor call?

### ISSUE THREAD

**Issue by ajdamico** [CSBLatvia/vardpoor#6]
hi, the minimal reproducible example below causes R to crash (not just error) at this line inside `variance_est`:

	z_hi <- hpY[, lapply(.SD, sum, na.rm = TRUE), keyby = c(names(hpY)[1:(2 + np + psusn)]), .SDcols = names(hpY)[-(1:(2 + np + psusn))]]

i suspect this is triggering something illegal in the `library(data.table)` C code but i am not too familiar with that syntax or how to write a useful bug report for matt dowle and arun srinivasan.  could you look at this console crash and (probably) file an issue with `data.table`?  thanks!

	# use development version of both
	devtools::install_github( "Rdatatable/data.table" )
	devtools::install_github("CSBLatvia/vardpoor/vardpoor")

	library(vardpoor)

	sessionInfo()
	# R version 3.3.2 (2016-10-31)
	# Platform: x86_64-w64-mingw32/x64 (64-bit)
	# Running under: Windows 10 x64 (build 10586)

	# locale:
	# [1] LC_COLLATE=English_United States.1252 
	# [2] LC_CTYPE=English_United States.1252   
	# [3] LC_MONETARY=English_United States.1252
	# [4] LC_NUMERIC=C                          
	# [5] LC_TIME=English_United States.1252    

	# attached base packages:
	# [1] stats     graphics  grDevices utils     datasets  methods   base     

	# other attached packages:
	# [1] vardpoor_0.8.4    stringr_1.1.0     laeken_0.4.6      MASS_7.3-45      
	# [5] boot_1.3-18       data.table_1.10.5 devtools_1.12.0  

	# loaded via a namespace (and not attached):
	 # [1] Rcpp_0.12.9.1      codetools_0.2-15   gtools_3.5.0       digest_0.6.12     
	 # [5] foreach_1.4.3      withr_1.0.2        plyr_1.8.4         R6_2.2.0          
	 # [9] git2r_0.16.0       magrittr_1.5       httr_1.2.1         stringi_1.1.2     
	# [13] curl_2.3           gdata_2.17.0       iterators_1.0.8    tools_3.3.2       
	# [17] surveyplanning_2.6 memoise_1.0.0     

	data(eusilc)
	names( eusilc ) <- tolower( names( eusilc ) )
	dati <- data.table(IDd = 1 : nrow(eusilc), eusilc)

	# CRASH R console
	varpoord_rmir_calculation <-
		varpoord(
		
			# analysis variable
			Y = "eqincome", 
			
			# weights variable
			w_final = "rb050",
			
			# row number variable
			ID_level1 = "IDd",
			
			# strata variable
			H = "db040", 
			
			N_h = NULL ,
			
			# clustering variable
			PSU = "rb030", 
			
			# data.table
			dataset = dati, 
			
			# rmir coefficient function
			type = "linrmir"
			
		)

**Comment by djhurio** [comment]
I am getting the following error with the stable versions of the packages. Thanks! We will take a look on this.

    Error in `:=`(variable, paste0("lin_", tolower(type))) : 
    Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

**Comment by ajdamico** [comment]
hmm, i get a crash.  if you're not on windows, is there any way you could get access to a windows machine to try to reproduce this?  i don't think it's related to #7 i think this is a bug in `data.table`?  thank you

**Comment by djhurio** [comment]
I am on Windows. And this is related to #7 as I am getting the same error message.

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
```

**Comment by ajdamico** [comment]
you're right.  i just re-installed the github versions and am no longer getting a crash.  thank you

**Comment by djhurio** [comment]
https://github.com/CSBLatvia/vardpoor/commit/f17c609429d789fec13cbecbc7d29f91773bbc03
