### ISSUE TITLE
varpoord type="lingpg" does not appear to be available?

### ISSUE THREAD

**Issue by ajdamico** [CSBLatvia/vardpoor#7]
`?varpoord` help file says it is but this straightforward calculation breaks, and `type="all_choices"` does not display it.  thanks!

	library(vardpoor)
	data(eusilc)
	names( eusilc ) <- tolower( names( eusilc ) )
	dati <- data.table(IDd = 1 : nrow(eusilc), eusilc)

	varpoord_gpg_calculation <-
		varpoord(
		
			# analysis variable
			Y = "eqincome", 
			
			# weights variable
			w_final = "rb050",
			
			# row number variable
			ID_level1 = "IDd",
			
			# strata variable
			H = "db040", 
			
			N_h = NULL ,
			
			# clustering variable
			PSU = "rb030", 
			
			# data.table
			dataset = dati, 
			
			# gpg coefficient function
			type = "lingpg"
			
		)

**Comment by ajdamico** [comment]
probably need to wait for https://github.com/CSBLatvia/vardpoor/issues/7

**Comment by djhurio** [comment]
Related to #6 .

**Comment by djhurio** [comment]
Corrected by https://github.com/CSBLatvia/vardpoor/commit/f17c609429d789fec13cbecbc7d29f91773bbc03
