### ISSUE TITLE
github version does not install

### ISSUE THREAD

**Issue by ajdamico** [CSBLatvia/vardpoor#8]
https://github.com/CSBLatvia/vardpoor/blob/master/vardpoor/R/vardchangespoor.R#L246

not sure if you've ever tried travis-ci, but it is awesome and would alert you to issues like this in the future?  it is free and well-designed for github.  here's ours:  https://travis-ci.org/DjalmaPessoa/convey  thanks

	> devtools::install_github("CSBLatvia/vardpoor/vardpoor")
	Downloading GitHub repo CSBLatvia/vardpoor@master
	from URL https://api.github.com/repos/CSBLatvia/vardpoor/zipball/master
	Installing vardpoor
	"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/anthonyd/AppData/Local/Temp/Rtmpk9F78l/devtools299460a2bcc/CSBLatvia-vardpoor-f17c609/vardpoor"  \
	  --library="C:/Users/anthonyd/Documents/R/win-library/3.3" --install-tests 

	* installing *source* package 'vardpoor' ...
	** R
	Error in parse(outFile) : 
	  C:/Users/anthonyd/AppData/Local/Temp/Rtmpk9F78l/devtools299460a2bcc/CSBLatvia-vardpoor-f17c609/vardpoor/R/vardchangespoor.R:246:6: unexpected 'if'
	245:       if (!all.equal(unique(gender), c(1, 2))) stop("'gender' must be value 1 for male, 2 for females")
	246:    } if
			  ^
	ERROR: unable to collate and parse R files for package 'vardpoor'
	* removing 'C:/Users/anthonyd/Documents/R/win-library/3.3/vardpoor'
	* restoring previous 'C:/Users/anthonyd/Documents/R/win-library/3.3/vardpoor'
	Error: Command failed (1)
	>

**Comment by JBreidaks** [comment]
https://github.com/CSBLatvia/vardpoor/commit/d5662f606c6ae3b19e7de5410ce456ae865bb681

**Comment by ajdamico** [comment]
thank you!
